settings:
  legacy:
    force: false
    interval: 0s
server:
  status: false
  open: false
  port: 5002
  host: localhost
schema:
  - name: web
    path: .
    commands:
      install:
        status: true
        method: go build -o .
      run:
        status: true
        method: /
    watcher:
      extensions:
        - go
      paths:
        - /
      ignore_paths:
        - .git
