settings:
  legacy:
    force: false
    interval: 0s
# server:
#   status: false
#   open: false
#   port: 8000
#   host: localhost
schema:
  - name: web
    # path: .
    commands:
      install:
        status: true
        method: go build -o /bin/realize
      run:
        status: true
        method: /bin/realize
    watcher:
      extensions:
        - go
      paths:
        - /
      ignore_paths:
        - .git
