settings:
    legacy:
      force: false
      interval: 0s
  schema:
  - name: hoge
    path: path/to/server
    commands:
      install:
        status: true
      run:
        status: true
    watcher:
      extensions:
      - go
      paths:
      - path/from/server
      ignore_paths:
      - .git