settings:
  legacy:
    force: false
    interval: 0s
schema:
  - name: web
    commands:
      install:
        status: true
        method: go build -o /bin/realize
      run:
        status: true
        method: /bin/realize
    watcher:
      extensions:
        - go
      paths:
        - /
      ignore_paths:
        - .git
